[versions]

agp = "8.9.2"
kotlin = "2.1.10"
ksp = "2.1.10-1.0.31"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
hilt = "2.55"
refresh-layout = "1.2.0-beta01"
room = "2.7.1"
retrofit = "2.11.0"
squareLogging = "4.12.0"
navVersion = "2.8.9"
serialization = "2.0.21"
sdp = "1.0.6"
coil = "3.0.3"
security = "1.1.0-alpha07"
starPrinter = "1.8.0"
firebaseBom = "33.12.0"
camera = "1.4.2"
barcode = "17.3.0"
workManager = "2.10.1"
zxing = "3.5.3"
gson = "2.11.0"
crashlytics = "3.0.3"
appDistribution = "5.1.1"
timber = "5.0.1"
legacySupportV4 = "1.0.0"
lifecycleLivedataKtx = "2.8.7"
lifecycleViewmodelKtx = "2.8.7"
fragmentKtx = "1.8.6"
turbine = "1.2.0"
mockIo = "1.14.0"
kotlin-coroutine-test = "1.10.2"
liveDataTest = "2.2.0"
fragmentTesting = "1.8.6"
navigationFragmentKtx = "2.9.3"
navigationUiKtx = "2.9.3"
mixPanel = "8.2.0"
flexbox = "3.0.0"

# Compose
composeBom = "2025.01.00"
activityCompose = "1.10.1"
navigationCompose = "2.8.9"
lifecycleRuntimeCompose = "2.8.7"
hiltNavigationCompose = "1.2.0"
coilCompose = "3.0.3"
runtime = "1.9.3"
accompanist = "0.36.0"
navigationTesting = "2.9.5"
runtimeLivedata = "1.9.3"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
mock-io = { group = "io.mockk", name = "mockk", version.ref = "mockIo" }
navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "navVersion" }
kotlin-coroutine-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlin-coroutine-test" }
live-data-test = { group = "androidx.arch.core", name = "core-testing", version.ref = "liveDataTest" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
swipe-refresh = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "refresh-layout" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-pagging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
refrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
refrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
square-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "squareLogging" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navVersion" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navVersion" }
sdp = { group = "com.intuit.sdp", name = "sdp-android", version.ref = "sdp" }
coil = { group = "io.coil-kt.coil3", name = "coil", version.ref = "coil" }
coil-network = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }
security = { group = "androidx.security", name = "security-crypto", version.ref = "security" }
starPrinter = { group = "com.starmicronics", name = "stario10", version.ref = "starPrinter" }
firebaseBom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
camera = { group = "androidx.camera", name = "camera-camera2", version.ref = "camera" }
camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "camera" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camera" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camera" }
camera-extension = { group = "androidx.camera", name = "camera-extensions", version.ref = "camera" }
mlkit-barcode = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "barcode" }
workManager = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManager" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
zxing = { group = "com.google.zxing", name = "core", version.ref = "zxing" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
androidx-legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
androidx-fragment-testing = { group = "androidx.fragment", name = "fragment-testing", version.ref = "fragmentTesting" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
mixpanel = { module = "com.mixpanel.android:mixpanel-android", version = "mixPanel" }
google-flexbox = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexbox" }

# Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeCompose" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coilCompose" }
androidx-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "runtime" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
androidx-navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "navigationTesting" }
androidx-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "runtimeLivedata" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
safe-args-gradle-plugin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navVersion" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
firebase-app-distribution = { id = "com.google.firebase.appdistribution", version.ref = "appDistribution" }


